# Generated by Django 2.2.7 on 2020-10-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_fiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fimg', models.CharField(max_length=200)),
                ('FictionName', models.CharField(max_length=200)),
                ('FWriterName', models.CharField(max_length=200)),
                ('Material', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Fiction',
        ),
    ]
